### ISSUE TITLE
Unable to download latest Serenity BDD CLI jar

### ISSUE THREAD

**Issue by abdul-farhat** [serenity-bdd/serenity-cli#3]
Hello! =)

Running npm test i get:

```
λ npm test

> tutorial-from-scripts-to-serenity@1.0.0 pretest C:\Users\farhata\github\tutorial-from-scripts-to-serenity
> serenity update

info: Looks like you need the latest Serenity BDD CLI jar. Let me download it for you...
error: Looks like an error occurred downloading the Serenity BDD CLI jar. 403

> tutorial-from-scripts-to-serenity@1.0.0 test C:\Users\farhata\github\tutorial-from-scripts-to-serenity
> failsafe clean protractor report

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! Test failed.  See above for more details.

```

Any ideas?

**Comment by wakaleo** [comment]
Thanks for raising this. This is a Bintray issue, not a serenity one as such; we have contacted Bintray to resolve the problem.

**Comment by abdul-farhat** [comment]
Any way to grab the jar files and drop them in the .cache dir manually?

**Comment by abdul-farhat** [comment]
The problem is now resolved.

**Comment by Purus** [comment]
Unable to download the jar file.. Is there any issue in bintray?

**Comment by damacus** [comment]
Hi looks like this has broken again with the same bintray problem.
